// Copyright (C) 2026 Cydral Technology (cydraltechnology@gmail.com)
// License: Boost Software License   See LICENSE.txt for the full license.
#undef DLIB_GGUF_WEIGHT_LOADER_ABSTRACT_H_
#ifdef DLIB_GGUF_WEIGHT_LOADER_ABSTRACT_H_

#include "gguf_reader_abstract.h"
#include "gguf_model_spec_abstract.h"

namespace dlib
{
    /*!
        OVERVIEW
            This header is the weight-repacking stage of the GGUF import pipeline.
            It dequantizes the tensors of a Llama-family GGUF file and copies them,
            with the required transpositions and permutations, into a Dlib network
            built from decoder_transformer_config (the type emitted by
            emit_header() in gguf_model_spec.h).

        WEIGHT LAYOUT
            - GGUF stores every 2D weight as [out, in] row-major; the Dlib linear
              and attention projections expect [in, out], so each matrix is
              transposed on load.
            - The fused attention layer holds one parameter tensor packed as
              [wq | wk | wv | wo (| gamma_q | gamma_k) | bq | bk | bv], with wq of
              shape [d_model, q_dim], wo of shape [q_dim, d_model] and wk, wv of
              shape [d_model, kv_dim], where q_dim = n_heads * head_dim and
              kv_dim = n_kv_heads * head_dim. The gamma slots exist only for
              QK-Norm models; the constant-layout bias slots stay zero for
              bias-free families and receive the QKV biases of the qwen2 family.
            - The SwiGLU feed-forward is three separate linear layers (gate, up,
              down).
            - Block RMSNorm gammas and the embedding table are copied directly,
              without transposition. The per-head QK-Norm gammas are not: they
              index the same output space as the Q/K projection rows, so they
              carry the rotary layout permutation, and the Q gamma additionally
              absorbs the 1 / sqrt(head_dim) attention prescale, which the
              normalization would otherwise erase (rms_norm(s * q) equals
              rms_norm(q)) since the score product does not reapply it.

        ROPE LAYOUT
            Two per-head orderings of the Q/K projection rows exist in the wild:
            the interleaved layout the Dlib rotary kernel uses, and the split-half
            (NeoX) layout. Llama-family GGUF files come pre-permuted for the
            interleaved kernel; the qwen families keep the NeoX layout and are
            permuted on load. Every quantity living in that same output space
            follows the same permutation: the QKV biases and the per-head QK-Norm
            gammas. V is rotation-free and is never permuted.

        VALIDATION PROCEDURE
            The two conventions that cannot be settled from metadata alone are
            exposed as knobs in gguf_load_options (rope_permute and swap_gate_up).
            The recommended procedure is to import, run a forward pass on a short
            prompt, and compare the first-position logits with a reference
            implementation. If they disagree, the cause is almost always one of
            the two knobs or the embedding orientation.
    !*/

    // ---------------------------------------------------------------------------------

    struct gguf_load_options
    {
        /*!
            WHAT THIS OBJECT REPRESENTS
                The options controlling import_gguf_weights().

            FIELDS
                rope_permute - Forces the split-half (NeoX) to interleaved
                               permutation of the Q/K projection rows even for
                               architectures that are not known to need it.
                               Default false: the permutation is applied
                               automatically for the qwen families and skipped for
                               llama-family files, which come pre-permuted.
                swap_gate_up - Swaps the mapping of the two inner SwiGLU linear
                               layers (ffn_gate and ffn_up). Default false.
                verbose      - Prints progress and RoPE diagnostics to standard
                               output during the import. Default true.
        !*/

        bool rope_permute = false;
        bool swap_gate_up = false;
        bool verbose = true;
    };

    // ---------------------------------------------------------------------------------

    template <typename net_type>
    void import_gguf_weights(
        net_type& net,
        gguf_reader& g,
        const model_spec& spec,
        const gguf_load_options& opt = gguf_load_options()
    );
    /*!
        requires
            - net_type is a network built from decoder_transformer_config with the
              exact dimensions described by spec (typically the network_type alias
              of the header generated by emit_header()).
            - spec == detect_model(g), and check_compatibility(spec) reported no
              blocker.
        ensures
            - Configures every attention layer of net with the model's runtime
              settings before any weight is touched: RoPE frequency base, QK-Norm
              epsilon, classical RoPE (YaRN disabled) and the QKV-bias flag
              (detected from the presence of blk.0.attn_q.bias in g). This runs
              before the first forward pass because the RoPE trigonometric caches
              are built then and are not recomputed on a later base change.
            - Pushes the model's RMSNorm epsilon into every normalization layer.
            - Runs a single one-token forward pass to allocate every parameter
              tensor, then leaves the global network_context reset.
            - Dequantizes and repacks every weight of g into the parameter tensors
              of net, in network visit order: lm_head (output.weight, or the
              embedding table when spec.tied_embeddings is true), the final norm,
              then each transformer block, and finally the embedding table.
            - Linear layers larger than their GGUF source (weights followed by an
              unused bias slot) have the trailing part zeroed.
            - When opt.verbose is true, prints the applied RoPE state and a block
              progress indicator to standard output.
        throws
            - std::runtime_error if a required tensor is missing from g, if a
              tensor does not match the expected size, or if the number of
              parameter tensors of net does not match the layer-order assumption
              (which indicates that net_type does not correspond to spec).
    !*/

    // ---------------------------------------------------------------------------------

}

#endif // DLIB_GGUF_WEIGHT_LOADER_ABSTRACT_H_
