// Copyright (C) 2026 Cydral Technology (cydraltechnology@gmail.com)
// License: Boost Software License   See LICENSE.txt for the full license.
#undef DLIB_DECODER_MODELS_ABSTRACT_H_
#ifdef DLIB_DECODER_MODELS_ABSTRACT_H_

#include "decoder_transformer_config_abstract.h"

namespace dlib
{
    /*!
        WHAT THIS FILE REPRESENTS
            A catalog of ready-to-instantiate decoder model structures. Each alias
            is a decoder_transformer_config matching a published open-weight model
            exactly: layer count, head geometry, embedding width, feed-forward
            ratio and vocabulary. They are usable on their own, independently of
            the GGUF import machinery, for training from scratch, fine-tuning, or
            as the typed counterpart of an imported model:

                using net_type = tinyllama_1_1b::network_type<false>;
                net_type net;

            Two run-time settings complete each structure, because they are values
            rather than shapes: the RMSNorm epsilon and the rotary frequency base.
            The documented per-model values are listed with each alias below; the
            GGUF import path applies them automatically from the container
            metadata, and standalone use applies them through the layer setters or
            the corresponding visitors before the first forward pass. The same
            holds for the QKV-bias flag of the families that carry projection
            biases (the bias slots exist in every attention layer and stay inert
            until enabled).

            These aliases and the headers generated by emit_header() (see
            gguf_model_spec.h in data_io) describe the same networks through the
            same decoder_transformer_config template; the catalog is the
            hand-curated set for well-known geometries, the generator covers any
            model detected from a GGUF file.

            Compilation cost scales with the layer count (every block is a
            distinct type); the shape-dynamic runtime engine is the alternative
            when only inference is needed.

        CATALOG
            - tinyllama_1_1b : TinyLlama 1.1B (chat v1.0 and derivatives).
                  vocab 32000, 22 layers, 32 heads / 4 KV, d_model 2048,
                  ffn 11/4 (5632). RMSNorm eps 1e-5, RoPE theta 10000.
                  Derivative fine-tunes sometimes extend the vocabulary
                  (e.g. 32003); substitute the first parameter accordingly.
            - smollm2_1_7b   : SmolLM2 1.7B (instruct).
                  vocab 49152, 24 layers, 32 heads / 32 KV (plain MHA),
                  d_model 2048, ffn 4/1 (8192), tied embeddings on import.
                  RMSNorm eps 1e-5, RoPE theta 130000.
            - llama2_7b      : Llama-2 7B.
                  vocab 32000, 32 layers, 32 heads / 32 KV, d_model 4096,
                  ffn 43/16 (11008). RMSNorm eps 1e-5, RoPE theta 10000.
            - mistral_7b     : Mistral 7B v0.1/v0.2 geometry.
                  vocab 32000, 32 layers, 32 heads / 8 KV, d_model 4096,
                  ffn 7/2 (14336). RMSNorm eps 1e-5, RoPE theta 10000 (v0.1)
                  or 1e6 (v0.2+).
            - llama3_8b      : Llama-3 8B.
                  vocab 128256, 32 layers, 32 heads / 8 KV, d_model 4096,
                  ffn 7/2 (14336). RMSNorm eps 1e-5, RoPE theta 500000.
            - qwen2_0_5b     : Qwen2 0.5B (instruct).
                  vocab 151936, 24 layers, 14 heads / 2 KV, d_model 896,
                  ffn 38/7 (4864), tied embeddings. RMSNorm eps 1e-6,
                  RoPE theta 1e6. This family carries QKV projection biases:
                  enable them at run time (the GGUF import does it
                  automatically from the tensor table).
            - qwen3_0_6b     : Qwen3 0.6B.
                  vocab 151936, 28 layers, 16 heads / 8 KV, d_model 1024,
                  ffn 3/1 (3072), explicit head_dim 128 (larger than
                  d_model / heads) and per-head QK normalization.
                  RMSNorm eps 1e-6, RoPE theta 1e6.
    !*/
}

#endif // DLIB_DECODER_MODELS_ABSTRACT_H_
