// Generated by slm_gguf_import. Source architecture: llama.
// Edit with care; regenerate from the source model when the spec changes.
#ifndef IMPORTED_MODEL_H_
#define IMPORTED_MODEL_H_

#include <dlib/dnn/decoder_transformer_config.h>

namespace imported_model
{
    static constexpr long VOCAB_SIZE    = 32000;
    static constexpr long NUM_LAYERS    = 22;
    static constexpr long NUM_HEADS     = 32;
    static constexpr long NUM_KV_HEADS  = 4;
    static constexpr long EMBEDDING_DIM = 2048;
    static constexpr long HEAD_DIM      = 64;
    static constexpr bool USE_QK_NORM   = false;
    static constexpr long FFN_NUM       = 11;  // hidden = EMBEDDING_DIM * FFN_NUM / FFN_DEN = 5632
    static constexpr long FFN_DEN       = 4;

    using config = dlib::decoder_transformer_config<
        VOCAB_SIZE, NUM_LAYERS, NUM_HEADS, NUM_KV_HEADS, EMBEDDING_DIM, FFN_NUM, FFN_DEN,
        HEAD_DIM, USE_QK_NORM>;

    // Strict model definition. network_type<false> is the inference network
    // (generation / chatbot); network_type<true> is the training network used
    // for fine-tuning. The imported weights are loaded into this exact type.
    template <bool is_training>
    using network_type = config::network_type<is_training>;

    // GGUF tensor names consumed by the weight-repacking stage:
    //   token_embd.weight, output_norm.weight, output.weight
    //   blk.{i}.attn_norm.weight
    //   blk.{i}.attn_q.weight, blk.{i}.attn_k.weight, blk.{i}.attn_v.weight, blk.{i}.attn_output.weight
    //   blk.{i}.ffn_norm.weight
    //   blk.{i}.ffn_gate.weight, blk.{i}.ffn_up.weight, blk.{i}.ffn_down.weight
}

#endif // IMPORTED_MODEL_H_
