// Generated by slm_gguf_import. Source architecture: qwen2.
// Edit with care; regenerate from the source model when the spec changes.
#ifndef DLIB_IMPORTED_QWEN2_0_5B_INSTRUCT_H_
#define DLIB_IMPORTED_QWEN2_0_5B_INSTRUCT_H_

#include <dlib/dnn/decoder_transformer_config.h>

namespace qwen2_0_5b_instruct
{
    // Identity of the imported model, for display and catalog selection.
    static const char* const MODEL_NAME = "qwen2-0_5b-instruct";

    static constexpr long VOCAB_SIZE    = 151936;
    static constexpr long NUM_LAYERS    = 24;
    static constexpr long NUM_HEADS     = 14;
    static constexpr long NUM_KV_HEADS  = 2;
    static constexpr long EMBEDDING_DIM = 896;
    static constexpr long HEAD_DIM      = 64;
    static constexpr bool USE_QK_NORM   = false;
    static constexpr long FFN_NUM       = 38;  // hidden = EMBEDDING_DIM * FFN_NUM / FFN_DEN = 4864
    static constexpr long FFN_DEN       = 7;

    using config = dlib::decoder_transformer_config<
        VOCAB_SIZE, NUM_LAYERS, NUM_HEADS, NUM_KV_HEADS, EMBEDDING_DIM, FFN_NUM, FFN_DEN,
        HEAD_DIM, USE_QK_NORM>;

    // Strict model definition. network_type<false> is the inference network
    // (generation / chatbot); network_type<true> is the training network used
    // for fine-tuning. The imported weights are loaded into this exact type.
    template <bool is_training>
    using network_type = config::network_type<is_training>;

    // GGUF tensor names consumed by the weight-repacking stage:
    //   token_embd.weight, output_norm.weight (output tied to token_embd)
    //   blk.{i}.attn_norm.weight
    //   blk.{i}.attn_q.weight, blk.{i}.attn_k.weight, blk.{i}.attn_v.weight, blk.{i}.attn_output.weight
    //   blk.{i}.ffn_norm.weight
    //   blk.{i}.ffn_gate.weight, blk.{i}.ffn_up.weight, blk.{i}.ffn_down.weight
}

/* The first imported-model header included in a translation unit claims the
   generic `imported_model` alias, so single-model programs compile unchanged
   whatever the model-specific namespace is. Programs embedding several models
   include several generated headers and use the explicit namespaces. */
#ifndef DLIB_IMPORTED_MODEL_ALIAS_DEFINED
#define DLIB_IMPORTED_MODEL_ALIAS_DEFINED
namespace imported_model = qwen2_0_5b_instruct;
#endif

#endif // DLIB_IMPORTED_QWEN2_0_5B_INSTRUCT_H_
